# Generated by Django 4.0.6 on 2022-07-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_wallet_address', models.CharField(max_length=100)),
                ('transaction_address', models.CharField(max_length=100)),
                ('card_brex_id', models.CharField(max_length=200)),
            ],
        ),
    ]
