# Generated by Django 4.0.6 on 2022-08-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(default='amac@paar.ai', max_length=254),
            preserve_default=False,
        ),
    ]
